name: main workflow (workflows/main.yaml)
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@v4
      - uses: facebook/install-dotslash@latest
      - run: echo "PATH=$(pwd):$PATH" >> $GITHUB_ENV
      - run: |-
          node --version
