name: main workflow (workflows/main.yaml)
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  run-tests:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    steps:
      - uses: actions/checkout@v4
      - uses: facebook/install-dotslash@latest
      - run: echo "PATH=$(pwd):$PATH" >> $GITHUB_ENV
      - run: echo "The node.js toolchain, version $(node --version)"
      - run: sudo npm install -g yarn
      - run: |-
          cd hello
          yarn add typescript --dev
          yarn tsc
          yarn node ./dist/app.js
          popd
